#include "lrun.h"
#include "SharedParameter.h"
#include "globals.h"
#include "vuser_init.c"
#include "kaas_DocSearchHPES_Doc_with_Products.c"
#include "kaas_DocSearchHPES_Doc_Categories.c"
#include "kaas_DocSearchHPES_Doc_without_Products.c"
#include "vuser_end.c"
